### ISSUE TITLE
Vad gör dessa?

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [theo-hiort-nti-johanneberg/2D_Game#3]
flytta till egen metod?

https://github.com/theo-hiort-nti-johanneberg/2D_Game/blob/85a8e85a32e3ffca24bd8ad1347846a7c2e29321/game.rb#L30-L37

**Comment by ntijoh-theo-hiort** [comment]
Bara målar upp rektanglarna där platformarna ska sitta för att få en visuell referens för vad X och Y värderna ska vara och hur tjocka/höga de ska vara. Dessa ska bli till egna objekt sedan men nu är de bara där för att se hur det skulle se ut.

**Comment by ntijoh-theo-hiort** [comment]
bara temporärt för att se hur det skulle se ut tills jag skapar en riktig klass för plattformar
